server {
    listen 80;
    server_name horizonr.iris.a3n.fr;
    charset utf-8;

    root /usr/share/nginx/html;

    location = / {
        return 302 /pages/login.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy vers le backend sur le reseau interne Docker
    location /api/ {
        proxy_pass http://horizonr-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
